Contact form branch
anbehindY/portfolio pull request #3
Opened 2023-02-21 18:40 UTC by why-a-en

In this branch
- We add a header like description to feel free to contact me
- We add a form that takes up three inputs of thier name, email address and the message they wish to leave
- The form is ended with a submit button 
- The whole webpage is finalized with a footer containing social links

2023-02-21 19:35 UTC, hiromataba requested changes
Hi @anbehindY    :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 19:35 UTC, hiromataba commented on index.html
> +        <fieldset>
- [ ] Please update your design to match the original design  the colors, outline for inputs and margin and colors

- Your Design 👇 

![image](https://user-images.githubusercontent.com/75126481/220440838-66ac24c3-8877-4718-9241-7634ec7b7dd5.png)

- Original Design 👇 

![image](https://user-images.githubusercontent.com/75126481/220440984-20503fd4-9237-4097-84a6-5fc833c25539.png)

2023-02-22 05:26 UTC, AbayomiOlaoye requested changes
Hi @anbehindY 🥇 👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://user-images.githubusercontent.com/99715640/211872359-9a4d36f7-0386-4000-82a4-c274b06a5ce4.gif)


 ## Highlights
- Great response to feedback from previous code reviewers ✅ 
- Great commit messages ✅ 
- No linter error ✅ 
- Nice implementation ✔️ 

 ## Required Changes ♻️
- [x] _Check the comments under the review._

## Optional suggestions
_N/A._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 05:26 UTC, AbayomiOlaoye commented on index.html
- [ ] Good job, @anbehindY 👍 however, just like the previous reviewer mentioned, your form is not consistent with the wireframe yet. I have helped to prepare a more explanatory schedule for comparison:

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/220528262-40bb47a4-3e69-4cda-9cd1-0baf8261a3ab.png)|![image](https://user-images.githubusercontent.com/99715640/220528156-f0471628-0873-4471-959b-c119dc8d3417.png)|

- Kindly notice the following:
  - The `border-bottom` line separating the inputs are too dark than the wireframe is.
  - Your `textarea` has physible border lines which are not present in the requirement.
  -  You seem to be missing the last aesthetic design at the the very bottom of the page.
 
Keep the good work, Champ 💯

2023-02-22 09:01 UTC, AlphaNtihinduka requested changes
## Hi @anbehindY 🙋‍♂️
Good job working on implementing the changes required by the previous reviewer. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- Kindly consider the inline comment.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-02-22 09:51 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @anbehindY, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter error. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/894d22fdf31aac32d1cd488fc22318df1eea3204fa6d0129c3d61a99f137ce2d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336b75536f3734345549504a6a634a55456e2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 09:54 UTC, merged